function [snapThreshPress , poreBodyFillThreshPress , layerColapseThreshPress] =...
    poreImbThreshPress(poreIndex,geometry,halfAngles,rec_angle,advancingingAngle,...
    inscribedR,shapeFactor,sig_ow,poreLayer)
%% pore body filling section
[poreBodyFillThreshPress , layerColapseThreshPress] =...
    poreBodyFillingThreshPress(poreIndex,poreLayer,advancingingAngle,...
    geometry,shapeFactor,inscribedR,halfAngles,rec_angle);
%% snap off section
snapThreshPress = snapThreshPressPoreThroat(geometry,halfAngles,...
    rec_angle,advancingingAngle,inscribedR,sig_ow);