function [snapThreshPress , pistonLikeThreshPress , oilLayerExist] = ...
    throatImbThreshPress(geometry,half_angles,rec_angle,adv_angle,inscribedR,G_factor,sig_ow)

[pistonLikeThreshPress,oilLayerExist] = pistonLikeThreshPressImb ...
    (geometry,half_angles,rec_angle,adv_angle,inscribedR,G_factor,sig_ow);

snapThreshPress = snapThreshPressPoreThroat(geometry,half_angles,...
    rec_angle,adv_angle,inscribedR,sig_ow);